# Site
title: 'MUMT618'
description: 'Driving-point admittance effects on the static playability of bowed strings'
tagline: 'A case study using simulations from a bowed string physical model including finite-width thermal friction and hair dynamics'
sidebar:
  - intro
  - minimum_bow_force
  - regime_estimation
  - regime_maps
  - results
  - bibliography

# Deployment
url:              https://lemonzi.github.io
baseurl:          /MUMT618

# Me
author:
  name:           'Quim Llimona'
  affiliation:    'McGill University'
  url:            http://lemonzi.me

# Ignore list
exclude:
  - Makefile
  - README.md
  - LICENSE.md

